GET http://localhost:5002/livros

###

GET http://localhost:5002/livros/1

###

POST http://localhost:5002/livros
Content-Type: application/json

{
  "titulo": "Dom Casmurro",
  "autor": "Machado de Assis",
  "areaId": 1,
  "ano": 1898,
  "editora": "Garnier"
}

###

PUT http://localhost:5002/livros/1
Content-Type: application/json

{
    "codigo":1,
    "titulo": "Dom Casmurro",
    "autor": "Machado de Assis",
    "area": "Literatura",
    "ano": 1898,
    "editora": "Garnier"
},