// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoBiblioteca.Api.Data;

#nullable disable

namespace ProjetoBiblioteca.Api.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20260131003942_AdicionaLivrosRestantes")]
    partial class AdicionaLivrosRestantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBiblioteca.Api.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("areas");
                });

            modelBuilder.Entity("ProjetoBiblioteca.Api.Models.Livro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .HasColumnType("longtext");

                    b.Property<string>("Editora")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("Codigo");

                    b.HasIndex("AreaId");

                    b.ToTable("livros");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Ano = 1965,
                            AreaId = 1,
                            Autor = "Frank Herbert",
                            Editora = "Aleph",
                            ImagemUrl = "",
                            Titulo = "Duna"
                        },
                        new
                        {
                            Codigo = 2,
                            Ano = 1937,
                            AreaId = 2,
                            Autor = "J.R.R. Tolkien",
                            Editora = "HarperCollins",
                            ImagemUrl = "",
                            Titulo = "O Hobbit"
                        },
                        new
                        {
                            Codigo = 3,
                            Ano = 1951,
                            AreaId = 1,
                            Autor = "Isaac Asimov",
                            Editora = "Aleph",
                            ImagemUrl = "",
                            Titulo = "Fundação"
                        },
                        new
                        {
                            Codigo = 4,
                            Ano = 1977,
                            AreaId = 3,
                            Autor = "Stephen King",
                            Editora = "Suma",
                            ImagemUrl = "",
                            Titulo = "O Iluminado"
                        },
                        new
                        {
                            Codigo = 5,
                            Ano = 1954,
                            AreaId = 2,
                            Autor = "J.R.R. Tolkien",
                            Editora = "Martins Fontes",
                            ImagemUrl = "",
                            Titulo = "O Senhor dos Anéis"
                        },
                        new
                        {
                            Codigo = 6,
                            Ano = 1984,
                            AreaId = 1,
                            Autor = "William Gibson",
                            Editora = "Aleph",
                            ImagemUrl = "",
                            Titulo = "Neuromancer"
                        },
                        new
                        {
                            Codigo = 7,
                            Ano = 1986,
                            AreaId = 3,
                            Autor = "Stephen King",
                            Editora = "Suma",
                            ImagemUrl = "",
                            Titulo = "It: A Coisa"
                        },
                        new
                        {
                            Codigo = 8,
                            Ano = 1997,
                            AreaId = 2,
                            Autor = "J.K. Rowling",
                            Editora = "Rocco",
                            ImagemUrl = "",
                            Titulo = "Harry Potter e a Pedra Filosofal"
                        },
                        new
                        {
                            Codigo = 9,
                            Ano = 1997,
                            AreaId = 4,
                            Autor = "Robert Kiyosaki",
                            Editora = "Alta Books",
                            ImagemUrl = "",
                            Titulo = "Pai Rico, Pai Pobre"
                        },
                        new
                        {
                            Codigo = 10,
                            Ano = 2007,
                            AreaId = 2,
                            Autor = "Patrick Rothfuss",
                            Editora = "Arqueiro",
                            ImagemUrl = "",
                            Titulo = "O Nome do Vento"
                        },
                        new
                        {
                            Codigo = 11,
                            Ano = 1949,
                            AreaId = 1,
                            Autor = "George Orwell",
                            Editora = "Companhia das Letras",
                            ImagemUrl = "",
                            Titulo = "1984"
                        },
                        new
                        {
                            Codigo = 12,
                            Ano = 1932,
                            AreaId = 1,
                            Autor = "Aldous Huxley",
                            Editora = "Biblioteca Azul",
                            ImagemUrl = "",
                            Titulo = "Admirável Mundo Novo"
                        },
                        new
                        {
                            Codigo = 13,
                            Ano = 1928,
                            AreaId = 3,
                            Autor = "H.P. Lovecraft",
                            Editora = "DarkSide",
                            ImagemUrl = "",
                            Titulo = "O Chamado de Cthulhu"
                        },
                        new
                        {
                            Codigo = 14,
                            Ano = 1818,
                            AreaId = 3,
                            Autor = "Mary Shelley",
                            Editora = "Zahar",
                            ImagemUrl = "",
                            Titulo = "Frankenstein"
                        },
                        new
                        {
                            Codigo = 15,
                            Ano = 1897,
                            AreaId = 3,
                            Autor = "Bram Stoker",
                            Editora = "DarkSide",
                            ImagemUrl = "",
                            Titulo = "Drácula"
                        },
                        new
                        {
                            Codigo = 16,
                            Ano = 2003,
                            AreaId = 6,
                            Autor = "Dan Brown",
                            Editora = "Arqueiro",
                            ImagemUrl = "",
                            Titulo = "O Código Da Vinci"
                        },
                        new
                        {
                            Codigo = 17,
                            Ano = 1887,
                            AreaId = 6,
                            Autor = "Arthur Conan Doyle",
                            Editora = "Zahar",
                            ImagemUrl = "",
                            Titulo = "Sherlock Holmes: Um Estudo em Vermelho"
                        },
                        new
                        {
                            Codigo = 18,
                            Ano = 1939,
                            AreaId = 6,
                            Autor = "Agatha Christie",
                            Editora = "Globo Livros",
                            ImagemUrl = "",
                            Titulo = "E Não Sobrou Nenhum"
                        },
                        new
                        {
                            Codigo = 19,
                            Ano = 1977,
                            AreaId = 2,
                            Autor = "J.R.R. Tolkien",
                            Editora = "HarperCollins",
                            ImagemUrl = "",
                            Titulo = "O Silmarillion"
                        },
                        new
                        {
                            Codigo = 20,
                            Ano = 1950,
                            AreaId = 2,
                            Autor = "C.S. Lewis",
                            Editora = "Martins Fontes",
                            ImagemUrl = "",
                            Titulo = "Crônicas de Nárnia"
                        },
                        new
                        {
                            Codigo = 21,
                            Ano = 1979,
                            AreaId = 1,
                            Autor = "Douglas Adams",
                            Editora = "Arqueiro",
                            ImagemUrl = "",
                            Titulo = "O Guia do Mochileiro das Galáxias"
                        },
                        new
                        {
                            Codigo = 22,
                            Ano = 1950,
                            AreaId = 1,
                            Autor = "Isaac Asimov",
                            Editora = "Aleph",
                            ImagemUrl = "",
                            Titulo = "Eu, Robô"
                        },
                        new
                        {
                            Codigo = 23,
                            Ano = 1898,
                            AreaId = 1,
                            Autor = "H.G. Wells",
                            Editora = "Suma",
                            ImagemUrl = "",
                            Titulo = "A Guerra dos Mundos"
                        },
                        new
                        {
                            Codigo = 24,
                            Ano = 1988,
                            AreaId = 4,
                            Autor = "Paulo Coelho",
                            Editora = "Paralela",
                            ImagemUrl = "",
                            Titulo = "O Alquimista"
                        },
                        new
                        {
                            Codigo = 25,
                            Ano = 2018,
                            AreaId = 4,
                            Autor = "James Clear",
                            Editora = "Alta Life",
                            ImagemUrl = "",
                            Titulo = "Hábitos Atômicos"
                        },
                        new
                        {
                            Codigo = 26,
                            Ano = 1899,
                            AreaId = 5,
                            Autor = "Machado de Assis",
                            Editora = "Principis",
                            ImagemUrl = "",
                            Titulo = "Dom Casmurro"
                        },
                        new
                        {
                            Codigo = 27,
                            Ano = 1956,
                            AreaId = 5,
                            Autor = "Guimarães Rosa",
                            Editora = "Companhia das Letras",
                            ImagemUrl = "",
                            Titulo = "Grande Sertão: Veredas"
                        },
                        new
                        {
                            Codigo = 28,
                            Ano = 1890,
                            AreaId = 5,
                            Autor = "Oscar Wilde",
                            Editora = "Pandorga",
                            ImagemUrl = "",
                            Titulo = "O Retrato de Dorian Gray"
                        },
                        new
                        {
                            Codigo = 29,
                            Ano = 1967,
                            AreaId = 5,
                            Autor = "Gabriel García Márquez",
                            Editora = "Record",
                            ImagemUrl = "",
                            Titulo = "Cem Anos de Solidão"
                        },
                        new
                        {
                            Codigo = 30,
                            Ano = 1845,
                            AreaId = 3,
                            Autor = "Edgar Allan Poe",
                            Editora = "DarkSide",
                            ImagemUrl = "",
                            Titulo = "O Corvo"
                        });
                });

            modelBuilder.Entity("ProjetoBiblioteca.Api.Models.Livro", b =>
                {
                    b.HasOne("ProjetoBiblioteca.Api.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });
#pragma warning restore 612, 618
        }
    }
}
